import { StyleSheet } from 'react-native';
import { remToPx } from '../../configs/text';

export const margin = StyleSheet.create({
  'm-0': { margin: 0 },
  'mx-0': { marginLeft: 0, marginRight: 0 },
  'my-0': { marginTop: 0, marginBottom: 0 },
  'mt-0': { marginTop: 0 },
  'mr-0': { marginRight: 0 },
  'mb-0': { marginBottom: 0 },
  'ml-0': { marginLeft: 0 },
  'm-px': { margin: 1 },
  'mx-px': { marginLeft: 1, marginRight: 1 },
  'my-': { marginTop: 1, marginBottom: 1 },
  'mt-': { marginTop: 1 },
  'mr-': { marginRight: 1 },
  'mb-': { marginBottom: 1 },
  'ml-': { marginLeft: 1 },
  'm-0.5': { margin: remToPx(0.125) },
  'mx-0.5': { marginLeft: remToPx(0.125), marginRight: remToPx(0.125) },
  'my-0.5': { marginTop: remToPx(0.125), marginBottom: remToPx(0.125) },
  'mt-0.5': { marginTop: remToPx(0.125) },
  'mr-0.5': { marginRight: remToPx(0.125) },
  'mb-0.5': { marginBottom: remToPx(0.125) },
  'ml-0.5': { marginLeft: remToPx(0.125) },
  'm-1': { margin: remToPx(0.25) },
  'mx-1': { marginLeft: remToPx(0.25), marginRight: remToPx(0.25) },
  'my-1': { marginTop: remToPx(0.25), marginBottom: remToPx(0.25) },
  'mt-1': { marginTop: remToPx(0.25) },
  'mr-1': { marginRight: remToPx(0.25) },
  'mb-1': { marginBottom: remToPx(0.25) },
  'ml-1': { marginLeft: remToPx(0.25) },
  'm-1.5': { margin: remToPx(0.375) },
  'mx-1.5': { marginLeft: remToPx(0.375), marginRight: remToPx(0.375) },
  'my-1.5': { marginTop: remToPx(0.375), marginBottom: remToPx(0.375) },
  'mt-1.5': { marginTop: remToPx(0.375) },
  'mr-1.5': { marginRight: remToPx(0.375) },
  'mb-1.5': { marginBottom: remToPx(0.375) },
  'ml-1.5': { marginLeft: remToPx(0.375) },
  'm-2': { margin: remToPx(0.5) },
  'mx-2': { marginLeft: remToPx(0.5), marginRight: remToPx(0.5) },
  'my-2': { marginTop: remToPx(0.5), marginBottom: remToPx(0.5) },
  'mt-2': { marginTop: remToPx(0.5) },
  'mr-2': { marginRight: remToPx(0.5) },
  'mb-2': { marginBottom: remToPx(0.5) },
  'ml-2': { marginLeft: remToPx(0.5) },
  'm-2.5': { margin: remToPx(0.625) },
  'mx-2.5': { marginLeft: remToPx(0.625), marginRight: remToPx(0.625) },
  'my-2.5': { marginTop: remToPx(0.625), marginBottom: remToPx(0.625) },
  'mt-2.5': { marginTop: remToPx(0.625) },
  'mr-2.5': { marginRight: remToPx(0.625) },
  'mb-2.5': { marginBottom: remToPx(0.625) },
  'ml-2.5': { marginLeft: remToPx(0.625) },
  'm-3': { margin: remToPx(0.75) },
  'mx-3': { marginLeft: remToPx(0.75), marginRight: remToPx(0.75) },
  'my-3': { marginTop: remToPx(0.75), marginBottom: remToPx(0.75) },
  'mt-3': { marginTop: remToPx(0.75) },
  'mr-3': { marginRight: remToPx(0.75) },
  'mb-3': { marginBottom: remToPx(0.75) },
  'ml-3': { marginLeft: remToPx(0.75) },
  'm-3.5': { margin: remToPx(0.875) },
  'mx-3.5': { marginLeft: remToPx(0.875), marginRight: remToPx(0.875) },
  'my-3.5': { marginTop: remToPx(0.875), marginBottom: remToPx(0.875) },
  'mt-3.5': { marginTop: remToPx(0.875) },
  'mr-3.5': { marginRight: remToPx(0.875) },
  'mb-3.5': { marginBottom: remToPx(0.875) },
  'ml-3.5': { marginLeft: remToPx(0.875) },
  'm-4': { margin: remToPx(1) },
  'mx-4': { marginLeft: remToPx(1), marginRight: remToPx(1) },
  'my-4': { marginTop: remToPx(1), marginBottom: remToPx(1) },
  'mt-4': { marginTop: remToPx(1) },
  'mr-4': { marginRight: remToPx(1) },
  'mb-4': { marginBottom: remToPx(1) },
  'ml-4': { marginLeft: remToPx(1) },
  'm-5': { margin: remToPx(1.25) },
  'mx-5': { marginLeft: remToPx(1.25), marginRight: remToPx(1.25) },
  'my-5': { marginTop: remToPx(1.25), marginBottom: remToPx(1.25) },
  'mt-5': { marginTop: remToPx(1.25) },
  'mr-5': { marginRight: remToPx(1.25) },
  'mb-5': { marginBottom: remToPx(1.25) },
  'ml-5': { marginLeft: remToPx(1.25) },
  'm-6': { margin: remToPx(1.5) },
  'mx-6': { marginLeft: remToPx(1.5), marginRight: remToPx(1.5) },
  'my-6': { marginTop: remToPx(1.5), marginBottom: remToPx(1.5) },
  'mt-6': { marginTop: remToPx(1.5) },
  'mr-6': { marginRight: remToPx(1.5) },
  'mb-6': { marginBottom: remToPx(1.5) },
  'ml-6': { marginLeft: remToPx(1.5) },
  'm-7': { margin: remToPx(1.75) },
  'mx-7': { marginLeft: remToPx(1.75), marginRight: remToPx(1.75) },
  'my-7': { marginTop: remToPx(1.75), marginBottom: remToPx(1.75) },
  'mt-7': { marginTop: remToPx(1.75) },
  'mr-7': { marginRight: remToPx(1.75) },
  'mb-7': { marginBottom: remToPx(1.75) },
  'ml-7': { marginLeft: remToPx(1.75) },
  'm-8': { margin: remToPx(2) },
  'mx-8': { marginLeft: remToPx(2), marginRight: remToPx(2) },
  'my-8': { marginTop: remToPx(2), marginBottom: remToPx(2) },
  'mt-8': { marginTop: remToPx(2) },
  'mr-8': { marginRight: remToPx(2) },
  'mb-8': { marginBottom: remToPx(2) },
  'ml-8': { marginLeft: remToPx(2) },
  'm-9': { margin: remToPx(2.25) },
  'mx-9': { marginLeft: remToPx(2.25), marginRight: remToPx(2.25) },
  'my-9': { marginTop: remToPx(2.25), marginBottom: remToPx(2.25) },
  'mt-9': { marginTop: remToPx(2.25) },
  'mr-9': { marginRight: remToPx(2.25) },
  'mb-9': { marginBottom: remToPx(2.25) },
  'ml-9': { marginLeft: remToPx(2.25) },
  'm-10': { margin: remToPx(2.5) },
  'mx-10': { marginLeft: remToPx(2.5), marginRight: remToPx(2.5) },
  'my-10': { marginTop: remToPx(2.5), marginBottom: remToPx(2.5) },
  'mt-10': { marginTop: remToPx(2.5) },
  'mr-10': { marginRight: remToPx(2.5) },
  'mb-10': { marginBottom: remToPx(2.5) },
  'ml-10': { marginLeft: remToPx(2.5) },
  'm-11': { margin: remToPx(2.75) },
  'mx-11': { marginLeft: remToPx(2.75), marginRight: remToPx(2.75) },
  'my-11': { marginTop: remToPx(2.75), marginBottom: remToPx(2.75) },
  'mt-11': { marginTop: remToPx(2.75) },
  'mr-11': { marginRight: remToPx(2.75) },
  'mb-11': { marginBottom: remToPx(2.75) },
  'ml-11': { marginLeft: remToPx(2.75) },
  'm-12': { margin: remToPx(3) },
  'mx-12': { marginLeft: remToPx(3), marginRight: remToPx(3) },
  'my-12': { marginTop: remToPx(3), marginBottom: remToPx(3) },
  'mt-12': { marginTop: remToPx(3) },
  'mr-12': { marginRight: remToPx(3) },
  'mb-12': { marginBottom: remToPx(3) },
  'ml-12': { marginLeft: remToPx(3) },
  'm-14': { margin: remToPx(3.5) },
  'mx-14': { marginLeft: remToPx(3.5), marginRight: remToPx(3.5) },
  'my-14': { marginTop: remToPx(3.5), marginBottom: remToPx(3.5) },
  'mt-14': { marginTop: remToPx(3.5) },
  'mr-14': { marginRight: remToPx(3.5) },
  'mb-14': { marginBottom: remToPx(3.5) },
  'ml-14': { marginLeft: remToPx(3.5) },
  'm-16': { margin: remToPx(4) },
  'mx-16': { marginLeft: remToPx(4), marginRight: remToPx(4) },
  'my-16': { marginTop: remToPx(4), marginBottom: remToPx(4) },
  'mt-16': { marginTop: remToPx(4) },
  'mr-16': { marginRight: remToPx(4) },
  'mb-16': { marginBottom: remToPx(4) },
  'ml-16': { marginLeft: remToPx(4) },
});
