import { StyleSheet } from 'react-native';
import { remToPx } from '../../configs/text';

export const padding = StyleSheet.create({
  'p-0': { padding: 0 },
  'px-0': { paddingLeft: 0, paddingRight: 0 },
  'py-0': { paddingTop: 0, paddingBottom: 0 },
  'pt-0': { paddingTop: 0 },
  'pr-0': { paddingRight: 0 },
  'pb-0': { paddingBottom: 0 },
  'pl-0': { paddingLeft: 0 },
  'p-px': { padding: 1 },
  'px-px': { paddingLeft: 1, paddingRight: 1 },
  'py-': { paddingTop: 1, paddingBottom: 1 },
  'pt-': { paddingTop: 1 },
  'pr-': { paddingRight: 1 },
  'pb-': { paddingBottom: 1 },
  'pl-': { paddingLeft: 1 },
  'p-0.5': { padding: remToPx(0.125) },
  'px-0.5': { paddingLeft: remToPx(0.125), paddingRight: remToPx(0.125) },
  'py-0.5': { paddingTop: remToPx(0.125), paddingBottom: remToPx(0.125) },
  'pt-0.5': { paddingTop: remToPx(0.125) },
  'pr-0.5': { paddingRight: remToPx(0.125) },
  'pb-0.5': { paddingBottom: remToPx(0.125) },
  'pl-0.5': { paddingLeft: remToPx(0.125) },
  'p-1': { padding: remToPx(0.25) },
  'px-1': { paddingLeft: remToPx(0.25), paddingRight: remToPx(0.25) },
  'py-1': { paddingTop: remToPx(0.25), paddingBottom: remToPx(0.25) },
  'pt-1': { paddingTop: remToPx(0.25) },
  'pr-1': { paddingRight: remToPx(0.25) },
  'pb-1': { paddingBottom: remToPx(0.25) },
  'pl-1': { paddingLeft: remToPx(0.25) },
  'p-1.5': { padding: remToPx(0.375) },
  'px-1.5': { paddingLeft: remToPx(0.375), paddingRight: remToPx(0.375) },
  'py-1.5': { paddingTop: remToPx(0.375), paddingBottom: remToPx(0.375) },
  'pt-1.5': { paddingTop: remToPx(0.375) },
  'pr-1.5': { paddingRight: remToPx(0.375) },
  'pb-1.5': { paddingBottom: remToPx(0.375) },
  'pl-1.5': { paddingLeft: remToPx(0.375) },
  'p-2': { padding: remToPx(0.5) },
  'px-2': { paddingLeft: remToPx(0.5), paddingRight: remToPx(0.5) },
  'py-2': { paddingTop: remToPx(0.5), paddingBottom: remToPx(0.5) },
  'pt-2': { paddingTop: remToPx(0.5) },
  'pr-2': { paddingRight: remToPx(0.5) },
  'pb-2': { paddingBottom: remToPx(0.5) },
  'pl-2': { paddingLeft: remToPx(0.5) },
  'p-2.5': { padding: remToPx(0.625) },
  'px-2.5': { paddingLeft: remToPx(0.625), paddingRight: remToPx(0.625) },
  'py-2.5': { paddingTop: remToPx(0.625), paddingBottom: remToPx(0.625) },
  'pt-2.5': { paddingTop: remToPx(0.625) },
  'pr-2.5': { paddingRight: remToPx(0.625) },
  'pb-2.5': { paddingBottom: remToPx(0.625) },
  'pl-2.5': { paddingLeft: remToPx(0.625) },
  'p-3': { padding: remToPx(0.75) },
  'px-3': { paddingLeft: remToPx(0.75), paddingRight: remToPx(0.75) },
  'py-3': { paddingTop: remToPx(0.75), paddingBottom: remToPx(0.75) },
  'pt-3': { paddingTop: remToPx(0.75) },
  'pr-3': { paddingRight: remToPx(0.75) },
  'pb-3': { paddingBottom: remToPx(0.75) },
  'pl-3': { paddingLeft: remToPx(0.75) },
  'p-3.5': { padding: remToPx(0.875) },
  'px-3.5': { paddingLeft: remToPx(0.875), paddingRight: remToPx(0.875) },
  'py-3.5': { paddingTop: remToPx(0.875), paddingBottom: remToPx(0.875) },
  'pt-3.5': { paddingTop: remToPx(0.875) },
  'pr-3.5': { paddingRight: remToPx(0.875) },
  'pb-3.5': { paddingBottom: remToPx(0.875) },
  'pl-3.5': { paddingLeft: remToPx(0.875) },
  'p-4': { padding: remToPx(1) },
  'px-4': { paddingLeft: remToPx(1), paddingRight: remToPx(1) },
  'py-4': { paddingTop: remToPx(1), paddingBottom: remToPx(1) },
  'pt-4': { paddingTop: remToPx(1) },
  'pr-4': { paddingRight: remToPx(1) },
  'pb-4': { paddingBottom: remToPx(1) },
  'pl-4': { paddingLeft: remToPx(1) },
  'p-5': { padding: remToPx(1.25) },
  'px-5': { paddingLeft: remToPx(1.25), paddingRight: remToPx(1.25) },
  'py-5': { paddingTop: remToPx(1.25), paddingBottom: remToPx(1.25) },
  'pt-5': { paddingTop: remToPx(1.25) },
  'pr-5': { paddingRight: remToPx(1.25) },
  'pb-5': { paddingBottom: remToPx(1.25) },
  'pl-5': { paddingLeft: remToPx(1.25) },
  'p-6': { padding: remToPx(1.5) },
  'px-6': { paddingLeft: remToPx(1.5), paddingRight: remToPx(1.5) },
  'py-6': { paddingTop: remToPx(1.5), paddingBottom: remToPx(1.5) },
  'pt-6': { paddingTop: remToPx(1.5) },
  'pr-6': { paddingRight: remToPx(1.5) },
  'pb-6': { paddingBottom: remToPx(1.5) },
  'pl-6': { paddingLeft: remToPx(1.5) },
  'p-7': { padding: remToPx(1.75) },
  'px-7': { paddingLeft: remToPx(1.75), paddingRight: remToPx(1.75) },
  'py-7': { paddingTop: remToPx(1.75), paddingBottom: remToPx(1.75) },
  'pt-7': { paddingTop: remToPx(1.75) },
  'pr-7': { paddingRight: remToPx(1.75) },
  'pb-7': { paddingBottom: remToPx(1.75) },
  'pl-7': { paddingLeft: remToPx(1.75) },
  'p-8': { padding: remToPx(2) },
  'px-8': { paddingLeft: remToPx(2), paddingRight: remToPx(2) },
  'py-8': { paddingTop: remToPx(2), paddingBottom: remToPx(2) },
  'pt-8': { paddingTop: remToPx(2) },
  'pr-8': { paddingRight: remToPx(2) },
  'pb-8': { paddingBottom: remToPx(2) },
  'pl-8': { paddingLeft: remToPx(2) },
  'p-9': { padding: remToPx(2.25) },
  'px-9': { paddingLeft: remToPx(2.25), paddingRight: remToPx(2.25) },
  'py-9': { paddingTop: remToPx(2.25), paddingBottom: remToPx(2.25) },
  'pt-9': { paddingTop: remToPx(2.25) },
  'pr-9': { paddingRight: remToPx(2.25) },
  'pb-9': { paddingBottom: remToPx(2.25) },
  'pl-9': { paddingLeft: remToPx(2.25) },
  'p-10': { padding: remToPx(2.5) },
  'px-10': { paddingLeft: remToPx(2.5), paddingRight: remToPx(2.5) },
  'py-10': { paddingTop: remToPx(2.5), paddingBottom: remToPx(2.5) },
  'pt-10': { paddingTop: remToPx(2.5) },
  'pr-10': { paddingRight: remToPx(2.5) },
  'pb-10': { paddingBottom: remToPx(2.5) },
  'pl-10': { paddingLeft: remToPx(2.5) },
  'p-11': { padding: remToPx(2.75) },
  'px-11': { paddingLeft: remToPx(2.75), paddingRight: remToPx(2.75) },
  'py-11': { paddingTop: remToPx(2.75), paddingBottom: remToPx(2.75) },
  'pt-11': { paddingTop: remToPx(2.75) },
  'pr-11': { paddingRight: remToPx(2.75) },
  'pb-11': { paddingBottom: remToPx(2.75) },
  'pl-11': { paddingLeft: remToPx(2.75) },
  'p-12': { padding: remToPx(3) },
  'px-12': { paddingLeft: remToPx(3), paddingRight: remToPx(3) },
  'py-12': { paddingTop: remToPx(3), paddingBottom: remToPx(3) },
  'pt-12': { paddingTop: remToPx(3) },
  'pr-12': { paddingRight: remToPx(3) },
  'pb-12': { paddingBottom: remToPx(3) },
  'pl-12': { paddingLeft: remToPx(3) },
  'p-14': { padding: remToPx(3.5) },
  'px-14': { paddingLeft: remToPx(3.5), paddingRight: remToPx(3.5) },
  'py-14': { paddingTop: remToPx(3.5), paddingBottom: remToPx(3.5) },
  'pt-14': { paddingTop: remToPx(3.5) },
  'pr-14': { paddingRight: remToPx(3.5) },
  'pb-14': { paddingBottom: remToPx(3.5) },
  'pl-14': { paddingLeft: remToPx(3.5) },
  'p-16': { padding: remToPx(4) },
  'px-16': { paddingLeft: remToPx(4), paddingRight: remToPx(4) },
  'py-16': { paddingTop: remToPx(4), paddingBottom: remToPx(4) },
  'pt-16': { paddingTop: remToPx(4) },
  'pr-16': { paddingRight: remToPx(4) },
  'pb-16': { paddingBottom: remToPx(4) },
  'pl-16': { paddingLeft: remToPx(4) },
});
